using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SpiderController : MonoBehaviour {

	public float moveSpeed;
	private bool canMove;

	private Rigidbody2D rigidBody;

	// Use this for initialization
	void Start () {
		canMove = false;
		rigidBody = GetComponent<Rigidbody2D>();
	}
	
	// Update is called once per frame
	void Update () {
		if(canMove) {
			rigidBody.velocity = new Vector3(-moveSpeed, rigidBody.velocity.y, 0f);
		}
	}

	void OnBecameVisible() {
		canMove = true;
	}

	void OnTriggerEnter2D(Collider2D other) {
		if(other.tag == "KillPlane") {
			gameObject.SetActive(false);
		}
	}

	void OnEnable() {
		canMove = false;
	}
}
